### ISSUE TITLE
htmlunit-plugin does not build with htmlunit 2.23

### ISSUE THREAD

**Issue by rapgro** [JWebUnit/jwebunit#4]
[ERROR] /builddir/build/BUILD/jwebunit-jwebunit-3.3/jwebunit-htmlunit-plugin/src/main/java/net/sourceforge/jwebunit/htmlunit/HtmlUnitTestingEngineImpl.java:[773,30] cannot find symbol
  symbol:   method getContent()
  location: class com.gargoylesoftware.htmlunit.xml.XmlPage

**Comment by henryju** [comment]
Fixed, thanks for reporting.
